version: "3.9"

services:
  backend:
    build: .
    container_name: algo-backend
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - SUPERVISOR_TOKEN=${SUPERVISOR_TOKEN:-changeme}

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algo-dashboard
    command: python -m algo_mvp.dashboard
    depends_on:
      - backend
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD:-password}
      - SUPERVISOR_URL=http://backend:8000
      # The supervisor_url above is the new way, keeping the old one for compatibility for now
      - supervisor_url=http://backend:8000
