services:
  backend:
    build: .
    container_name: algo-backend
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs:ro
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - SUPERVISOR_TOKEN=${SUPERVISOR_TOKEN:-changeme}
      - ALPACA_KEY_ID=${ALPACA_KEY_ID:-dummy}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY:-dummy}
      - TRADOVATE_CLIENT_ID=${TRADOVATE_CLIENT_ID:-dummy}
      - TRADOVATE_PASSWORD=${TRADOVATE_PASSWORD:-dummy}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s # How often to run the check
      timeout: 10s  # How long to wait for a response
      retries: 5    # How many times to retry before marking as unhealthy
      start_period: 60s # Extended start period to give more time for initialization

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algo-dashboard
    command: python -m algo_mvp.dashboard
    depends_on:
      backend:
        condition: service_healthy # Wait for backend to be healthy
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD:-password}
      - SUPERVISOR_URL=http://backend:8000
      # The supervisor_url above is the new way, keeping the old one for compatibility for now
      - supervisor_url=http://backend:8000
