# Supervisor API connection URL
# This should point to your running supervisor instance
supervisor_url = "http://localhost:8000"

# Dashboard password protection
# This password is required to access the dashboard UI
dashboard_password = "your-secure-password-here"
